services:

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092" # port exposé pour Windows
    environment:
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_NODE_ID=1
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      # Listeners internes pour Docker et externe pour Windows
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://<IP_WINDOWS>:9092,PLAINTEXT_INTERNAL://kafka:29092
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT_INTERNAL
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
    volumes:
      - kafka_data:/var/lib/kafka/data

  spark:
    image: apache/spark:3.5.3
    container_name: spark
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.master.Master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4040:4040"
    volumes:
      - .:/opt/spark/work-dir
    depends_on:
      - kafka

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"

volumes:
  kafka_data:
